### ISSUE TITLE
Difference between exports & module.exports

### ISSUE THREAD

**Issue by sammdec** [jackfranklin/react-training-workshop#2]
Hey Jack, 
Just looking though some of the code yesterday and notice that in your routes file your exporting the routes object as just `exports.routes = ...` (https://github.com/jackfranklin/react-training-workshop/blob/master/exercises/universal-react/routes.js#L5) but in your components when your export them you set them as `module.exports = ...`.

Is there any big reason for this?

**Comment by jackfranklin** [comment]
Hey Sam,

Sorry it's taken me so long to get back to you on this one.

I will use `exports.X` when I expect the module to export many things, and `module.exports` when the module only exports one thing.

In this case I'd actually probably update the code to use `module.exports` - not sure why I went with `exports.routes`, in hindsight!
